### ISSUE TITLE
Email does not exist

### ISSUE THREAD

**Issue by staminna** [devgson/soshace-rbac#2]
I was able to run the postman examples successfully, although the login route is returning

> Error: Email does not exist
    at exports.login (/soshace-rbac/server/controllers/userController.js:68:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

I can see the email, token and every other information in MongoDB compass also
I set the x-access-token into the headers.
I also send in postman Email and password. Do I need JWT token somewhere also somewhere?

**Comment by devgson** [comment]
Hello Jorge,
Sorry for the late reply, I'll take a look at the issue and get back to you
as soon as possible.

**Comment by staminna** [comment]
Hello devgson,
I found out I was passing the wrong arguments to postman.
Thanks very much.
